config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :monsters
  get 'maps/show'

  resources :game_boards do
    resource :portals, only: [ :show ]
    resource :in_the_news, only: [ :show ]
    resource :game_board_logs, only: [ :show ]
    resources :investigators do
      resource :game_action_logs, only: [:show ]
      resource :investigator_actions, only: [:show ]
      get :movement_selection
      post :move_start
      get :investigate
      get :ask_people
      get :find_portal
      get :close_portal
      get :combat_monster
      post :set_destination
      get :follow_path
    end
    get :next_turn
    get :start_game
  end

  get 'start_admin' => 'admin#start_admin'
  get 'stop_admin' => 'admin#stop_admin'
  get 'new_investigator_name/:gender' => 'investigators#new_name'

  resources :travels do
    post :wayback
  end
  resources :places
  resources :professions

  root 'game_boards#index'

end

app/controllers/investigators_controller.rb
class InvestigatorsController < ApplicationController
  before_action :set_investigator, only: [:show, :edit, :update, :destroy, :investigate, :ask_people, :find_portal, :close_portal, :combat_monster, :set_destination, :follow_path  ]
  before_action :set_current_game_board, except: [ :new_name ]

  include InvestigatorsActions::Movement
  include InvestigatorsActions::ClueFinding

  # GET /investigators
  # GET /investigators.json
  def index
    @investigators = Investigator.where( game_board_id: @current_game_board )
    @investigators.each do |investigator|
      investigator.game_action.check_action
    end
  end

  # GET /investigators/1
  # GET /investigators/1.json
  def show
  end

  # GET /investigators/new
  def new
    @investigator = Investigator.new
    initialize_investigator
  end

  # GET /investigators/1/edit
  def edit
  end

  # POST /investigators
  # POST /investigators.json
  def create
    @investigator = Investigator.new(investigator_params)

    profession = Profession.find( params[ :investigator ][ :profession_id ] )
    @investigator.influence = profession.influence
    @investigator.observation = profession.observation
    @investigator.will= profession.will
    @investigator.combat= profession.combat
    @investigator.sanity= profession.sanity
    @investigator.stamina= profession.stamina
    @investigator.game_board = @current_game_board

    action = Ga::Waiting.new( location_id: profession.start_place_id )
    action.save!
    @investigator.game_action = action

    respond_to do |format|
      if @investigator.save
        format.html { redirect_to game_board_investigators_path( @current_game_board ), notice: 'Investigator was successfully created.' }
        format.json { render :show, status: :created, location: @investigator }
      else
        format.html { render new_game_board_investigator_path(@current_game_board ) }
        format.json { render json: @investigator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investigators/1
  # PATCH/PUT /investigators/1.json
  def update
    respond_to do |format|
      if @investigator.update(investigator_params)
        format.html { redirect_to [ @current_game_board, @investigator ], notice: 'Investigator was successfully updated.' }
        format.json { render :show, status: :ok, location: @investigator }
      else
        format.html { render new_game_board_investigator_path(@current_game_board ) }
        format.json { render json: @investigator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investigators/1
  # DELETE /investigators/1.json
  def destroy
    @investigator.destroy
    respond_to do |format|
      format.html { redirect_to [ @current_game_board, @investigator ], notice: 'Investigator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_name
    @gender = params[ :gender ]
    render layout: false
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_investigator
      @investigator = Investigator.find( params[:id] || params[:investigator_id] )
      @investigator.game_action.check_action
    end

    def set_current_game_board
      @current_game_board = GameBoard.find(params[:game_board_id] )
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def investigator_params
      params.require(:investigator).permit(:name, :gender, :profession_id)
    end

    def initialize_investigator
      @investigator.gender= :m
      @investigator.name = Investigator.generate_name( :m )
    end
end

app/helpers/investigators_helper.rb
module InvestigatorsHelper

  def destination( travel )
    destination = travel.place_to
    if destination
      ( destination.full_description_name )
    end
  end

  def neighbours( travel )
    destination = travel.place_to
    destination.neighbours.map{ |e| e.name_with_article }.sort.join( ', ')
  end

  def lead_to( travel )
    destination = travel.place_to
    lead_to_places = []
    neighbours = destination.neighbours.to_a
    destination.neighbours.each do |place|
      place.neighbours.each do |final_place|
        lead_to_places << final_place unless lead_to_places.include?( final_place ) || neighbours.include?( final_place )
      end
    end
    lead_to_places.map{ |e| e.name_with_article }.sort.join( ', ' )
  end

end

app/views/investigators/_form.html.haml
= form_for [ @current_game_board, @investigator ] do |f|
  - if @investigator.errors.any?
    #error_explanation
      %h2= "#{pluralize(@investigator.errors.count, "error")} prohibited this investigator from being saved:"
      %ul
        - @investigator.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name, :readonly => true
    \
    %button#change_name{ type: :button } Change name

  .field
    = f.label :Male
    = f.radio_button( :gender, :m, class: :gender_selector )
    = f.label :Female
    = f.radio_button( :gender, :f, class: :gender_selector )

  .field
    = f.label :profession
    = f.select( :profession_id, Profession.all.map { |p| [ p.name, p.id ] } )

  .actions
    = f.submit 'Save'

app/views/investigators/ask_people.html.haml
%h1= t '.title'

%h2= @result

= link_to 'Back', game_board_investigators_path( @current_game_board )

app/views/investigators/edit.html.haml
%h1 Editing investigator

= render 'form'

= link_to 'Show', [ @current_game_board, @investigator ]
\|
= link_to 'Back', game_board_investigators_path

app/views/investigators/index.html.haml
%h1 Listing investigators

%table.table
  %thead
    %tr
      %th Name
      %th Profession
      %th Location
      %th Clues
      %th Actions
      %th
      %th
      %th
      %th

  %tbody
    - @investigators.each do |investigator|
      - action_data = investigator.game_action.print_action_data
      %tr
        %td
          - if investigator.incapacited
            %strike
              = investigator.name
          - else
            = investigator.name
        %td= investigator.profession.name
        %td
          = action_data[ :location_to_print ]
          %span{ class: :eta_show_area, id: "eta_show_area_#{investigator.id}", eta: action_data[ :eta_int ] }
            = action_data[ :eta_str ]
        %td= investigator.clues
        %td= investigator.actions_count
        %td= button_to 'Actions', game_board_investigator_investigator_actions_path( @current_game_board, investigator ), method: :get, class: 'btn btn-default' unless investigator.incapacited
        %td= link_to 'Show', [ @current_game_board, investigator ]
        %td= link_to 'Edit', edit_game_board_investigator_path( @current_game_board, investigator )
        %td= link_to 'Destroy', [ @current_game_board, investigator ], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= next_turn_link
|
= link_to 'New Investigator', new_game_board_investigator_path( @current_game_board )

app/views/investigators/investigate_a_place.html.haml
%br

= @result

%br

= link_to 'Back', game_board_investigators_path( @current_game_board )

app/views/investigators/move.html.haml
%h1 Avlaiable travels

%table
  %thead
    %tr
      %th Destination
      %th

  %tbody
    - @travels.each do |travel|
      %tr
        %td= name_with_ancestors( travel.place_to )
        %td= link_to 'Start travel', game_board_investigator_move_start_path( @current_game_board, @investigator, travel_destination: travel.id ), method: :post

app/views/investigators/movement_selection.html.haml
%h4 Available travels

.row
  .col-lg-4
    = render partial: 'in_the_news/in_the_news'
  .col-lg-8
    %table.table
      %thead
        %tr
          %th Destination
          %th Second
          %th Third
          %th

      %tbody
        - @travels.each do |travel|
          %tr
            %td= destination( travel )
            %td= neighbours( travel )
            %td= lead_to( travel )
            %td= button_to 'Start travel', game_board_investigator_move_start_path( @current_game_board, @investigator, travel_destination: travel.id ), class: 'btn btn-default'

app/views/investigators/new.html.haml
%h1 New investigator

= render 'form'

= link_to 'Back', game_board_investigators_path

app/views/investigators/new_name.html.haml
= Investigator.generate_name( @gender )

app/views/investigators/read_the_news.html.haml
%h1 Reading the news you find the following informations

%ul
  - @in_the_news_places.each do |in_the_news|
    %li= news_info( in_the_news )

app/views/investigators/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @investigator.name
%p
  %b Location:
  = @investigator.game_action.inspect

= link_to 'Edit', edit_game_board_investigator_path( @current_game_board, @investigator )
\|
= link_to 'Back', game_board_investigators_path( @current_game_board )