config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :monsters
  get 'maps/show'

  resources :game_boards do
    resource :portals, only: [ :show ]
    resource :in_the_news, only: [ :show ]
    resource :game_board_logs, only: [ :show ]
    resources :investigators do
      resource :game_action_logs, only: [:show ]
      resource :investigator_actions, only: [:show ]
      get :movement_selection
      post :move_start
      get :investigate
      get :ask_people
      get :find_portal
      get :close_portal
      get :combat_monster
      post :set_destination
      get :follow_path
    end
    get :next_turn
    get :start_game
  end

  get 'start_admin' => 'admin#start_admin'
  get 'stop_admin' => 'admin#stop_admin'
  get 'new_investigator_name/:gender' => 'investigators#new_name'

  resources :travels do
    post :wayback
  end
  resources :places
  resources :professions

  root 'game_boards#index'

end

app/models/monster.rb
class Monster < ActiveRecord::Base

  has_and_belongs_to_many :places

  def cleaned_default_translation
    default_translation.downcase.gsub( /[^a-z]/, '_' )
  end

  def name
    I18n.t( "monsters.#{code}", default: default_translation )
  end

end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: [:show, :edit, :update, :destroy]

  # GET /monsters
  # GET /monsters.json
  def index
    @monsters = Monster.all
  end

  # GET /monsters/1
  # GET /monsters/1.json
  def show
  end

  # GET /monsters/new
  def new
    @monster = Monster.new
    @monster.hit_points, @monster.willpower_test, @monster.horror, @monster.combat_test, @monster.damages, @monster.apparition_weight = session[ :last_monster_info ]
    set_places
    check_places
  end

  # GET /monsters/1/edit
  def edit
    set_places
    check_places
  end

  # POST /monsters
  # POST /monsters.json
  def create
    @monster = Monster.new(monster_params)

    @monster.code = @monster.cleaned_default_translation

    session[ :last_monster_info ] = [ @monster.hit_points, @monster.willpower_test, @monster.horror, @monster.combat_test, @monster.damages, @monster.apparition_weight ]

    respond_to do |format|
      if @monster.save
        @monster.place_ids = params[ :places ]
        format.html { redirect_to @monster, notice: 'Monster was successfully created.' }
        format.json { render :show, status: :created, location: @monster }
      else
        format.html { render :new }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monsters/1
  # PATCH/PUT /monsters/1.json
  def update
    respond_to do |format|
      if @monster.update(monster_params)
        @monster.place_ids = params[ :places ]
        format.html { redirect_to @monster, notice: 'Monster was successfully updated.' }
        format.json { render :show, status: :ok, location: @monster }
      else
        format.html { render :edit }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monsters/1
  # DELETE /monsters/1.json
  def destroy
    @monster.destroy
    respond_to do |format|
      format.html { redirect_to monsters_url, notice: 'Monster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monster
      @monster = Monster.find(params[:id])
    end

    def check_places
      @checked_places = @monster.places.select( :id ).map{ |e| e.id }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monster_params
      params.require(:monster).permit(:default_translation, :hit_points, :willpower_test, :horror, :combat_test, :damages, :apparition_weight)
    end

    def set_places
      @places = Place.where( city: false  ).order( 'default_translation' ).map { |p| [ p.full_description_name, p.id ] }
    end

end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/monsters/_form.html.haml
= form_for @monster, html: { class: 'form-horizontal' } do |f|
  - if @monster.errors.any?
    #error_explanation
      %h2= "#{pluralize(@monster.errors.count, "error")} prohibited this monster from being saved:"
      %ul
        - @monster.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save', class: 'btn btn-default'
    = submit_tag :select_all, type: :button, id: :select_all, class: 'btn btn-default', data: {disable_with: "Submitting..."}

  .row
    .col-lg-4
      .form-group
        = f.label :default_translation, class: 'col-sm-5 control-label'
        .col-sm-7
          = f.text_field :default_translation, class: 'form-control'

      .form-group
        = f.label :hit_point, class: 'col-sm-9 control-label'
        .col-sm-3
          = f.number_field :hit_points, class: 'form-control'

      .form-group
        = f.label :willpower_test, class: 'col-sm-9 control-label'
        .col-sm-3
          = f.number_field :willpower_test, class: 'form-control'

      .form-group
        = f.label :horror, class: 'col-sm-9 control-label'
        .col-sm-3
          = f.number_field :horror, class: 'form-control'

      .form-group
        = f.label :combat_test, class: 'col-sm-9 control-label'
        .col-sm-3
          = f.number_field :combat_test, class: 'form-control'

      .form-group
        = f.label :damages, class: 'col-sm-9 control-label'
        .col-sm-3
          = f.number_field :damages, class: 'form-control'

      .form-group
        = f.label :apparition_weight, class: 'col-sm-9 control-label'
        .col-sm-3
          = f.number_field :apparition_weight, class: 'form-control'


    - if @places.size > 0
      - @places.each_slice( ( @places.size / 2.0 ).ceil ) do |places_in_column|

        .col-lg-3
          .field
            %table
              - places_in_column.each do |place|
                %tr
                  %td= f.label place[ 0 ]
                  %td= check_box_tag 'places[]', place[ 1 ], @checked_places.include?( place[ 1 ] ), class: :monster_place_checkbox

app/views/monsters/edit.html.haml
%h3 Editing monster

= render 'form'

= button_to 'Show', @monster, method: :get, class: 'btn btn-default'
= button_to 'Back', monsters_path, method: :get, class: 'btn btn-default'

app/views/monsters/index.html.haml
%h3 Listing monsters

= button_to 'New Monster', new_monster_path, method: :get, class: 'btn btn-default'

%table.table
  %thead
    %tr
      %th Code
      %th Default translation
      %th Hit points
      %th Willpower test
      %th Horror
      %th Combat test
      %th Damages
      %th Apparition weight
      %th
      %th
      %th

  %tbody
    - @monsters.each do |monster|
      %tr
        %td= monster.code
        %td= monster.default_translation
        %td= monster.hit_points
        %td= monster.willpower_test
        %td= monster.horror
        %td= monster.combat_test
        %td= monster.damages
        %td= monster.apparition_weight
        %td= link_to 'Show', monster
        %td= link_to 'Edit', edit_monster_path(monster)
        %td= link_to 'Destroy', monster, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= button_to 'New Monster', new_monster_path, method: :get, class: 'btn btn-default'

app/views/monsters/new.html.haml
%h3 New monster

= render 'form'

= button_to 'Back', monsters_path, method: :get, class: 'btn btn-default'

app/views/monsters/show.html.haml
%p#notice= notice

%p
  %b Code:
  = @monster.code
%p
  %b Default translation:
  = @monster.default_translation
%p
  %b Hit points:
  = @monster.hit_points
%p
  %b Willpower test:
  = @monster.willpower_test
%p
  %b Horror:
  = @monster.horror
%p
  %b Combat test:
  = @monster.combat_test
%p
  %b Damages:
  = @monster.damages
%p
  %b Apparition weight:
  = @monster.apparition_weight

= link_to 'Edit', edit_monster_path(@monster)
\|
= link_to 'Back', monsters_path