config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :monsters
  get 'maps/show'

  resources :game_boards do
    resource :portals, only: [ :show ]
    resource :in_the_news, only: [ :show ]
    resource :game_board_logs, only: [ :show ]
    resources :investigators do
      resource :game_action_logs, only: [:show ]
      resource :investigator_actions, only: [:show ]
      get :movement_selection
      post :move_start
      get :investigate
      get :ask_people
      get :find_portal
      get :close_portal
      get :combat_monster
      post :set_destination
      get :follow_path
    end
    get :next_turn
    get :start_game
  end

  get 'start_admin' => 'admin#start_admin'
  get 'stop_admin' => 'admin#stop_admin'
  get 'new_investigator_name/:gender' => 'investigators#new_name'

  resources :travels do
    post :wayback
  end
  resources :places
  resources :professions

  root 'game_boards#index'

end

app/models/clue.rb
class Clue < ActiveRecord::Base
  belongs_to :game_board
  belongs_to :place
end

app/models/game_action.rb
class GameAction < ActiveRecord::Base

  attr_reader :action_result

  has_one :investigator
  belongs_to :location, class_name: 'Place', foreign_key: :location_id
  belongs_to :travel, class_name: 'Travel', foreign_key: :travel_id

  def check_action
    # Default check action is nothing : will be overloaded by some actions.
  end

  private

  def terminate_action
    investigator.update_attribute( :actions_count, investigator.actions_count - 1 )
    game_board = investigator.game_board
    actions_points_count = 0
    game_board.avaliable_investigators.each do |investigator|
      actions_points_count += investigator.actions_count
    end
    if actions_points_count <= 0
      game_board.next_turn
    end
  end

  def check_for_monster
    game_board_id = investigator.game_board_id
    MonsterOnBoard.find_by_game_board_id_and_place_id( game_board_id, location_id )
  end

end

app/models/game_action_log.rb
class GameActionLog < ActiveRecord::Base
  belongs_to :investigator
  belongs_to :action_location, class_name: 'Place', foreign_key: :action_location_id
  belongs_to :result_location, class_name: 'Place', foreign_key: :result_location_id
end

app/models/game_board.rb
class GameBoard < ActiveRecord::Base

  PRESAGES = [ :comet, :eclipse, :constellation, :star ]
  MAX_TURNS = 20
  INVESTIGATORS_ACTIONS_POINTS = 3

  include GameBoardSetting::TurnManagement

  has_many :investigators, dependent: :destroy
  has_many :avaliable_investigators, -> { where( mad: false, dead: false ) }, class_name: 'Investigator', foreign_key: :game_board_id

  has_many :game_action_logs, through: :investigators, class_name: 'GameActionLog'

  has_many :clues, dependent: :destroy
  has_many :places_where_there_are_clues, class_name: 'Place', through: :clues, source: :place

  has_many :in_the_news_places, dependent: :destroy
  has_many :places_where_the_news_says_there_are_clues, class_name: 'Place', through: :in_the_news_places, source: :place

  has_many :portals, dependent: :destroy
  has_many :places_with_portals, class_name: 'Place', through: :portals, source: :place
  has_many :discovered_portals, -> { where( discovered: true ) }, class_name: 'Portal'
  has_many :undiscovered_portals, -> { where( discovered: false ) }, class_name: 'Portal'
  has_many :places_with_discovered_portals, class_name: 'Place', through: :discovered_portals, source: :place

  has_many :portals, dependent: :destroy
  has_many :game_board_logs, -> { order 'created_at desc' }, dependent: :destroy

  has_many :monster_on_boards
  has_many :monsters, class_name: 'Monster', through: :monster_on_boards, source: :monster

end

app/models/game_board_log.rb
class GameBoardLog < ActiveRecord::Base
  belongs_to :game_board
end

app/models/indice.rb
class Indice < ActiveRecord::Base
  belongs_to :game_board
  belongs_to :place
end

app/models/item.rb
class Item < ActiveRecord::Base

  has_and_belongs_to_many :places, join_table: :items_can_be_found_at_places

end

app/models/monster.rb
class Monster < ActiveRecord::Base

  has_and_belongs_to_many :places

  def cleaned_default_translation
    default_translation.downcase.gsub( /[^a-z]/, '_' )
  end

  def name
    I18n.t( "monsters.#{code}", default: default_translation )
  end

end

app/models/monster_on_board.rb
class MonsterOnBoard < ActiveRecord::Base
  belongs_to :game_board
  belongs_to :monster
  belongs_to :place
end

app/models/place.rb
class String
  def capitalize_first
    (slice(0) || '').upcase + (slice(1..-1) || '')
  end

  def capitalize_first!
    replace(capitalize_first)
  end
end

class Place < ActiveRecord::Base

  include Language::Articles

  has_closure_tree
  has_many :game_actions, dependent: :destroy, foreign_key: :location_id

  has_many :travels, foreign_key: :place_from_id
  has_many :neighbours, class_name: 'Place', foreign_key: :place_to_id, through: :travels, source: :place_to

  has_and_belongs_to_many :monsters

  # Example : la gare a Arkham
  def full_description_name
    unless city
      parent_string = parent ? parent.name_with_preposition : ''
      ( name_with_article + ' ' + parent_string ).capitalize_first
    else
      translated_name
    end
  end

  # Example : a la gare d'Arkham, aux quais d'Arkham, a Arkham
  def full_localisation_name
    if well_known_place
      parent_string = parent ? ' ' + parent.name_with_preposition : ''
    else
      parent_string = parent ? ', ' + parent.name_with_spatial_preposition_building_or_place : ''
    end
    name_with_spatial_preposition_building_or_place + parent_string
  end

  def parent_with_locative_prep
    parent ? parent.name_with_locative_prep : ''
  end

  def cleaned_default_translation
    default_translation.downcase.gsub( /[^a-z]/, '_' )
  end

  # De, du, d'
  def name_with_preposition
    if city
      ( preposition + translated_name.capitalize )
    else
      ( preposition + translated_name )
    end
  end

  # A - a la - au - aux
  def name_with_spatial_preposition_building_or_place
    result = ( locative_prep + ' ' + translated_name )

    unless city
      if gender == 'f'
        result = ( locative_prep + ' ' + definite_article + translated_name )
      elsif gender == 'm'
        vowels = I18n.t( 'vowels' )
        place_name = translated_name
        if vowels.include?( place_name[ 0 ].downcase )
          result = ( 'a' + ' ' + definite_article + translated_name )
        end
      end
    else
      result = ( locative_prep + ' ' + translated_name.capitalize )
    end

    result
  end

  # Le - la - les
  def name_with_article
    definite_article + translated_name
  end

  private

  def translated_name
    I18n.t( "places.#{cleaned_code}", default: default_translation )
  end

  # Du - de - la - de l'
  def name_with_partitive_article
    partitive_article + translated_name.capitalize
  end

  def cleaned_code
    code.downcase.gsub( /[^a-z]/, '_' )
  end

end

app/models/portal.rb
class Portal < ActiveRecord::Base
  belongs_to :game_board
  belongs_to :place
end

app/models/profession.rb
class Profession < ActiveRecord::Base

  belongs_to :start_place, class_name: 'Place'
  has_many :investigators, dependent: :destroy

  COMP_POINTS = 10
  HEALTH_POINTS = 10

end

app/models/travel.rb
class Travel < ActiveRecord::Base

  belongs_to :place_from, class_name: 'Place'
  belongs_to :place_to, class_name: 'Place'

end

app/controllers/investigator_actions_controller.rb
class InvestigatorActionsController < ApplicationController

  include InvestigatorsActions::ClueFinding

  def show
    @current_game_board = GameBoard.find(params[:game_board_id] )
    @investigator = Investigator.find( params[:id] || params[:investigator_id] )
    @investigator.game_action.check_action
    @game_action_log = @investigator.game_action_logs.limit( 5 )
    @discovered_portals = @current_game_board.discovered_portals
    @monsters_in_place = MonsterOnBoard.where( place_id: @investigator.game_action.location_id, game_board_id: @current_game_board.id )
    setup_in_the_news_places
  end

end

app/helpers/investigator_actions_helper.rb
module InvestigatorActionsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/helpers/places_helper.rb
module PlacesHelper

  # def name_with_ancestors( place )
  #   ( [ place.name ] + place.ancestors.map{ |e| e.name } ).join( ' - ' )
  # end

end

app/helpers/portals_helper.rb
module PortalsHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/investigator_actions/_actions.html.haml
- action_data = @investigator.game_action.print_action_data
= action_data[ :location_to_print ]
%span{ class: :eta_show_area, id: "eta_show_area_#{@investigator.id}", eta: action_data[ :eta_int ] }
  = action_data[ :eta_str ]

.list-group
  - if @investigator.has_actions
    = link_to 'Move', game_board_investigator_movement_selection_path( @current_game_board, @investigator), class: 'list-group-item'
    - if @investigator.destination_id && @investigator.destination_id != @investigator.game_action.location_id
      = link_to 'Follow path', game_board_investigator_follow_path_path( @current_game_board, @investigator), class: 'list-group-item'
    = link_to 'Investigate a place', game_board_investigator_investigate_path( @current_game_board, @investigator), class: 'list-group-item'
    = link_to t( '.ask_people' ), game_board_investigator_ask_people_path( @current_game_board, @investigator), class: 'list-group-item'
    = link_to 'Trouver un portail', game_board_investigator_find_portal_path( @current_game_board, @investigator), class: 'list-group-item'
    = link_to 'Fermer un portail', game_board_investigator_close_portal_path( @current_game_board, @investigator), class: 'list-group-item'
    = link_to 'Combattre un monstre', game_board_investigator_combat_monster_path( @current_game_board, @investigator), class: 'list-group-item'
    = link_to t( '.show_log' ), game_board_investigator_game_action_logs_path( @current_game_board, @investigator), class: 'list-group-item'

app/views/investigator_actions/_discovered_portals.html.haml
%table.table
  %tr
    %th
      Portals locations
  - @discovered_portals.each do |portal|
    %tr
      %td= portal.place.full_description_name
      %td= portal.presage

app/views/investigator_actions/_game_action_log.html.haml
%table.table
  %tr
    %th{ colspan: 2 }
      Game actions
  - @game_action_log.each do |log|
    %tr
      %td= log.updated_at.strftime( '%T' )
      %td
        = t( '.' + log.action_type ) + ' ' + current_location_name( log ) + '.'
        = t( "actions_results.#{log.action_type}.#{log.result_code}", location: result_location_name( log ) )

app/views/investigator_actions/_investigator.html.haml
%table.table
  %tr
    %th{ colspan: 4 }= @investigator.name
  %tr
    %td{ colspan: 4 }
      - action_data = @investigator.game_action.print_action_data
      = action_data[ :location_to_print ]
      %span{ class: :eta_show_area, id: "eta_show_area_#{@investigator.id}", eta: action_data[ :eta_int ] }
        = action_data[ :eta_str ]
  %tr
    %td= 'Indices'
    %td= @investigator.clues
    %td= 'Actions'
    %td= @investigator.actions_count
  %tr
    %td= 'Sanity'
    %td= @investigator.sanity
    %td= 'Stamina'
    %td= @investigator.stamina
  %tr
    %td= 'Observation'
    %td= @investigator.observation
    %td= 'Influence'
    %td= @investigator.influence
  %tr
    %td= 'Volontée'
    %td= @investigator.will
    %td= 'Combat'
    %td= @investigator.combat

app/views/investigator_actions/_monster_in_place.html.haml
%table.table
  %tr
    %th
      Monstre(s)
  - @monsters_in_place.each do |monster_place|
    %tr
      %td
        = link_to( monster_place.monster.name, monster_place.monster )

app/views/investigator_actions/show.html.haml
%h4 Investigator Actions

= button_to 'Investigator', game_board_investigators_path( @current_game_board ), method: :get, class: 'btn btn-default'

%br

.row
  .col-lg-6
    = render partial: 'in_the_news/in_the_news'
  .col-lg-6
    = render partial: 'actions'

.row
  .col-lg-6
    = render partial: 'discovered_portals'
  .col-lg-6
    = render partial: 'monster_in_place'

.row
  .col-lg-6
    = render partial: 'game_action_log'
  .col-lg-6
    = render partial: 'investigator'